name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            .dart_tool/
            build/
            .flutter-plugins
            .flutter-plugins-dependencies
            pubspec.lock
            example/.dart_tool/
            example/build/
            example/.flutter-plugins
            example/.flutter-plugins-dependencies
            example/pubspec.lock
          key: ${{ runner.OS }}-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/*.dart') }}
          restore-keys: |
            ${{ runner.OS }}-

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

      - run: flutter pub get

      - name: Run tests
        working-directory: example
        run: flutter test --coverage --coverage-path=../coverage/lcov.info --coverage-package=golden_screenshot

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Test fixes
        working-directory: test_fixes
        run: dart fix --compare-to-golden
